In [31]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import joblib
import numpy as np
import tensorflow as tf

In [6]:
# Connecting Google Drive and Google Colab
from google.colab import drive
drive.mount('/content/gdrive')

# Retrieving Dataset
dataset = '/content/gdrive/MyDrive/Credit Score Classification Dataset.csv'
df = pd.read_csv(dataset)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [7]:
df

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000,Master's Degree,Married,2,Owned,High
2,35,Female,75000,Doctorate,Married,1,Owned,High
3,40,Male,125000,High School Diploma,Single,0,Owned,High
4,45,Female,100000,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...,...
159,29,Female,27500,High School Diploma,Single,0,Rented,Low
160,34,Male,47500,Associate's Degree,Single,0,Rented,Average
161,39,Female,62500,Bachelor's Degree,Married,2,Owned,High
162,44,Male,87500,Master's Degree,Single,0,Owned,High
163,49,Female,77500,Doctorate,Married,1,Owned,High

In [9]:
def normalize_data(age, gender, income, education, marital_status, number_of_children, home_ownership):
    normalization_model = "normalization_model.joblib"
    # Load the saved scaler using joblib
    scaler = joblib.load(normalization_model)
    data = np.array([[age, gender, income, education, marital_status, number_of_children, home_ownership]])
   # Normalize the data using Joblib
    normalized_data = scaler.transform(data)
    return normalized_data

def predict(normalize_data):
    # Load the TensorFlow model
    model = "model.h5"
    model = tf.keras.models.load_model(model)
    predictions = model.predict(normalize_data)
    return predictions

In [24]:
x = normalize_data(30,	0,	8075000.0,	3,	1,	2,	1)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [25]:
predict(x)

1/1 [==============================] - 0s 68ms/step

array([[4.9462173e-08, 8.1018428e-04, 9.9918979e-01]], dtype=float32)

In [27]:
# Mendapatkan indeks nilai maksimum
predicted_class = np.argmax([4.9462173e-08, 8.1018428e-04, 9.9918979e-01])

# Definisikan label kelas sesuai dengan indeks maksimum
class_labels = ['Pragmatic', 'Progresif', 'Pioneering']
predicted_label = class_labels[predicted_class]

In [28]:
predicted_label

'Pioneering'